// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26/12/2025, 14:15:30
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Admin/Documents/Projetos/mercadinho/painel-admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Documents/Projetos/mercadinho/painel-admin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Documents/Projetos/mercadinho/painel-admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Documents/Projetos/mercadinho/painel-admin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Documents/Projetos/mercadinho/painel-admin/plugins/**/*.{js,ts,mjs}","C:/Users/Admin/Documents/Projetos/mercadinho/painel-admin/composables/**/*.{js,ts,mjs}","C:/Users/Admin/Documents/Projetos/mercadinho/painel-admin/utils/**/*.{js,ts,mjs}","C:/Users/Admin/Documents/Projetos/mercadinho/painel-admin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Documents/Projetos/mercadinho/painel-admin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Documents/Projetos/mercadinho/painel-admin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Documents/Projetos/mercadinho/painel-admin/app.config.{js,ts,mjs}","C:/Users/Admin/Documents/Projetos/mercadinho/painel-admin/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;